# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='abbrev',
        ),
        migrations.AddField(
            model_name='airport',
            name='icao',
            field=models.CharField(default=None, max_length=4, unique=True),
        ),
    ]
