# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_auto_20171206_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
